apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssh-app
  name: ssh-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-app
  template:
    metadata:
      creationTimestamp: "2022-01-01T00:00:00Z"
      labels:
        app: ssh-app
    spec:
      containers:
        - name: ssh-app
          image: rastasheep/ubuntu-sshd:18.04
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      hostname: ssh-app
      restartPolicy: Always
