apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: ssh-app
  name: ssh-app
spec:
  type: LoadBalancer
  ports:
    - name: "22"
      port: 22
      targetPort: 22
  selector:
    app: ssh-app
status:
  loadBalancer: {}
