apiVersion: v1
kind: Service
metadata:
  name: ssh-app
  namespace: default
  labels:
    app: ssh-app
spec:
  type: NodePort
  ports:
    - name: "ssh"
      port: 22
      nodePort: 30036
  selector:
    app: ssh-app
status:
  loadBalancer: {}
